require:
  - rubocop

AllCops:
 TargetRubyVersion: 3.0.3
 Exclude:
   - 'bin/**/*'
   - 'vendor/**/*'
   - 'db/**/*'
   - 'config/**/*'
   - 'script/**/*'
   - 'spec/rails_helper.rb'
   - 'spec/spec_helper.rb'

Documentation:
 Enabled: false

Layout/LineLength:
  Max: 140