default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV.fetch("PG_USERNAME") %>
  password: <%= ENV.fetch("PG_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_service_development

test:
  <<: *default
  database: api_service_test

production:
  <<: *default
  database: api_service_production
  username: api_service
  password: <%= ENV["API_SERVICE_DATABASE_PASSWORD"] %>